version: "3"

services:
  castle:
    image: traefik:2.0
    command: --configFile=/opt/castle/traefik.toml
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.config/castle:/opt/castle
    labels:
      - "traefik.HTTP.Services.Castle.LoadBalancer.server.Port=8080"
